name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    name: Run renovate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'
      - name: Show existing package versions
        continue-on-error: true
        run: python3 -m pip install test_renovate==9999 # fake version to trigger error
        env:
          PIP_EXTRA_INDEX_URL: https//test.pypi.org/simple
      - name: Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          configurationFile: renovate.json
          token: ${{ github.token }}
          renovate-version: full
        env:
          UV_NATIVE_TLS: "true"
          LOG_LEVEL: 'debug'

